# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/15_download_models.ipynb.

# %% auto 0
__all__ = ['download_paddleocr_models']

# %% ../nbs/15_download_models.ipynb 2
def download_paddleocr_models(lang: str = 'en') -> None:
    from paddleocr import PaddleOCR
    PaddleOCR(
        use_doc_orientation_classify=False,
        use_doc_unwarping=False,
        use_textline_orientation=True,
        lang=lang,
    )

