# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/main.ipynb.

# %% auto 0
__all__ = ['api']

# %% ../nbs/main.ipynb 2
from fastapi import FastAPI

try:
    from pipeline.routers.spatial import router as spatial_router
except Exception:
    from routers.spatial import router as spatial_router


api = FastAPI()


@api.on_event("startup")
def _startup_load_models():
    try:
        try:
            from pipeline.angle_detection.angle_predictor import _load_angle_models
        except Exception:
            from angle_detection.angle_predictor import _load_angle_models

        _load_angle_models()
    except Exception:
        pass


api.include_router(spatial_router, prefix="/api", tags=["spatial"])

